#!/usr/bin/env bash
# Recompile requirements.lock from requirements.in for the release's one target
# (CPython 3.12, macOS arm64), pinned to the versions the developer lock already
# uses wherever the two sets overlap, with hashes so the build installs exactly
# these files. Run after changing requirements.in or api/uv.lock.
set -euo pipefail
cd "$(dirname "$0")"
REPO="$(cd ../.. && pwd)"
constraints="$(mktemp)"
trap 'rm -f "$constraints"' EXIT
uv export --frozen --no-dev --no-hashes --no-emit-project --directory "$REPO/api" -q > "$constraints"
uv pip compile requirements.in -c "$constraints" --python-version 3.12 \
  --python-platform aarch64-apple-darwin --generate-hashes --no-header --no-annotate -q -o requirements.lock
echo "✓ requirements.lock"

# The optional larger search model's runtime (G182 phase 3): sentence-transformers and what it needs beyond the
# bundled set, at the developer lock's versions, hashed. It ships inside the app (api/data/) and is installed with
# `pip --require-hashes --no-deps` into ~/.cicada/extras only when the person asks for the larger model.
full="$(mktemp)"
trap 'rm -f "$constraints" "$full"' EXIT
printf 'sentence-transformers\n' | uv pip compile - -c "$constraints" --python-version 3.12 \
  --python-platform aarch64-apple-darwin --generate-hashes --no-header --no-annotate -q -o "$full"
/usr/bin/python3 - "$full" requirements.lock "$REPO/api/data/extras-requirements.lock" <<'PY'
import re, sys
full, base, out = sys.argv[1:4]
def blocks(path):
    text = open(path, encoding="utf-8").read()
    return re.findall(r"^([A-Za-z0-9_.-]+)==[^\n]*(?:\n[ \t]+[^\n]*)*", text, re.M), text
names = lambda path: {n.lower().replace("_", "-") for n in re.findall(r"^([A-Za-z0-9_.-]+)==", open(path).read(), re.M)}
# Locked for the bundle but removed from it by build-backend.sh (keep the two lists in step;
# test_embedding_models holds them): the extras need them back.
PRUNED = {"sympy", "mpmath", "hf-xet"}
bundled = names(base) - PRUNED
text = open(full, encoding="utf-8").read()
keep = [m.group(0) for m in re.finditer(r"^([A-Za-z0-9_.-]+)==[^\n]*(?:\n[ \t]+[^\n]*)*", text, re.M)
        if m.group(1).lower().replace("_", "-") not in bundled]
header = ("# G182 — the optional larger search model's runtime, beyond what the app bundles.\n"
          "# Generated by scripts/release/lock-requirements.sh; installed with --require-hashes --no-deps.\n")
open(out, "w", encoding="utf-8").write(header + "\n".join(keep) + "\n")
print(f"✓ api/data/extras-requirements.lock ({len(keep)} packages)")
PY
