local H=require('ase_helpers')
local ART=app.params.art or app.fs.joinPath(H.scriptDir(),'..')
local dir=app.fs.joinPath(ART,'qa/helper-tests'); H.ensureDir(dir)
local pal=H.palette({{'K','#090707','worm.outline'},{'G','#9CC460','worm.body'}})
assert(H.hex('#01020304')==1); assert(H.palette({G={'#9CC460','x'}}).index.G==1)
local im=H.image(5,5); assert(im:isEmpty())
H.px(im,-1,0,pal,'K'); H.rect(im,1,1,3,3,pal,'G'); H.line(im,0,0,4,4,pal,'K')
H.erase(im,2,2); assert(im:getPixel(2,2)==0)
H.stamp(im,{'G_','..'},0,0,pal); assert(im:getPixel(1,0)==0)
local grid=H.grid({'GK','K.'},pal,{flipX=true,map={G='K'}}); assert(grid:getPixel(1,0)==pal.px.K)
assert(not pcall(function() H.grid({'?'},pal) end))
local out=H.image(6,6); H.paste(out,im,1,1); assert(out:getPixel(1,1)==pal.px.G)
assert(H.scaled(grid,3).width==6)
local q=H.quantize(grid,pal); assert(q:getPixel(1,0)==pal.px.K)
local swapped=H.recolor(H.grid({'KG'},pal),pal,{K='G',G='K'}); assert(swapped:getPixel(0,0)==pal.px.G and swapped:getPixel(1,0)==pal.px.K)
assert(H.inkBounds(H.image(1,1))==nil)
assert(H.unionRect({x=1,y=2,w=2,h=3},{x=0,y=0,w=1,h=1}).h==5)
local spr,l=H.newSprite(6,6,pal,{'ref','body'}); assert(H.findLayer(spr,'body')==H.layer(spr,'body'))
local rec=H.recorder(spr); rec:start('one'); rec:frame(1001,{body={image=im,x=1,y=1}}); rec:copy(1,1400); rec:stop(); rec:apply()
assert(H.ms(spr.frames[1])==1001 and #spr.tags==1)
H.setDuration(spr.frames[2],1002); assert(H.ms(spr.frames[2])==1002)
H.setCel(spr,'ref',1,grid); l.ref.isVisible=false
assert(H.flatten(spr,1):getPixel(0,0)==0); assert(H.assertPalette(spr,pal))
local bounds=H.spriteInk(spr); assert(bounds.x==1 and bounds.y==1)
H.addSlice(spr,'ink',bounds); assert(spr.slices[1].name=='ink')
H.save(spr,app.fs.joinPath(dir,'parts.aseprite'))
assert(H.loadPart(app.fs.joinPath(dir,'parts.aseprite'),'one').width==6)
assert(not pcall(function() H.loadPart(app.fs.joinPath(dir,'parts.aseprite'),'missing') end))
H.writePaletteJson(app.fs.joinPath(dir,'pal.json'),pal,{version='test'})
assert(H.paletteFromJson(app.fs.joinPath(dir,'pal.json')).px.K==pal.px.K)
H.writeJson(app.fs.joinPath(dir,'ledger.json'),H.ledger(spr)); assert(H.readJson(app.fs.joinPath(dir,'ledger.json')).frames==2)
H.exportPng(im,app.fs.joinPath(dir,'image.png'),2)
assert(H.loadReference(app.fs.joinPath(dir,'image.png'),5,5,pal).width==5)
H.exportFramePng(spr,1,app.fs.joinPath(dir,'frame.png'),2)
H.exportSheet(spr,app.fs.joinPath(dir,'sheet.png'),app.fs.joinPath(dir,'sheet.json'))
H.exportGif(spr,app.fs.joinPath(dir,'one.gif'),'one',2)
assert(app.fs.isFile(app.fs.joinPath(dir,'one.gif')))
H.setCel(spr,'ref',1,H.grid({'G'},pal)); assert(H.assertPalette(spr,pal))
local bad=H.image(1,1); bad:drawPixel(0,0,app.pixelColor.rgba(1,2,3,99)); H.setCel(spr,'ref',1,bad)
assert(not pcall(function() H.assertPalette(spr,pal) end))
spr:close(); print('helpers: every public helper and additions passed')
